package com.miaoshaproject.dataobject;

public class UserPasswordDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbg.generated Thu Mar 07 16:29:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.user_id
     *
     * @mbg.generated Thu Mar 07 16:29:21 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encrptPassword
     *
     * @mbg.generated Thu Mar 07 16:29:21 CST 2019
     */
    private String encrptpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.id
     *
     * @return the value of user_password.id
     *
     * @mbg.generated Thu Mar 07 16:29:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.id
     *
     * @param id the value for user_password.id
     *
     * @mbg.generated Thu Mar 07 16:29:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.user_id
     *
     * @return the value of user_password.user_id
     *
     * @mbg.generated Thu Mar 07 16:29:21 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.user_id
     *
     * @param userId the value for user_password.user_id
     *
     * @mbg.generated Thu Mar 07 16:29:21 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.encrptPassword
     *
     * @return the value of user_password.encrptPassword
     *
     * @mbg.generated Thu Mar 07 16:29:21 CST 2019
     */
    public String getEncrptpassword() {
        return encrptpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.encrptPassword
     *
     * @param encrptpassword the value for user_password.encrptPassword
     *
     * @mbg.generated Thu Mar 07 16:29:21 CST 2019
     */
    public void setEncrptpassword(String encrptpassword) {
        this.encrptpassword = encrptpassword == null ? null : encrptpassword.trim();
    }
}